# Generated by Django 4.1.1 on 2022-10-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('p_desc', models.TextField()),
                ('p_input', models.TextField()),
                ('p_output', models.TextField()),
            ],
        ),
    ]
