# Generated by Django 4.1.1 on 2022-10-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='p_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='p_input',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='p_output',
            new_name='output',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_id',
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
